# Generated using https://godot-build-options-generator.github.io

production = "yes"
disable_3d = "yes"
brotli = "no"
module_bmp_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_mobile_vr_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_upnp_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
